sudo: required
dist: trusty

language: python
python: 3.6

env:
  - TOX_ENV=py36

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install:
 - pip install tox

before_script:
  - docker-compose up -d --build

script:
  - tox -e $TOX_ENV

after_script:
  - docker-compose down